const no = {
 "403": "403 - Forbudt, du er ikke innlogget og har ingen tilgang.",
  "404": "404 - Ressurs ikke tilgjengelig, hvis du mener dette er feil - sjekk at du er innlogget.",
  "500": "500 - Intern feil på server",
  about: "Om",
  aboutToPlay: "Partiet ditt starter snart!",
  acceptDraw: "Aksepter remis?",
  accountDoesNotExist: "Kontoen eksisterer ikke.",
  accountHasNoEmail: "Kontoen er opprettet uten e-post ",
  accountList: "Kontoliste",
  accountSettings: "Kontoinnstillinger",
  add: "Legg til",
  addATeam: "Legg til et lag",
  addClub: "Legg til en klubb",
  addMember: "Legg til medlem",
  addOtherAccount: "Legg til en konto",
  addPairing: "Legg til rundeoppsett",
  addParticipantsWithAccount: "Legg til deltakere med konto",
  addParticipantsWithoutAccount: "Legg til deltakere uten konto",
  addRound: "Legg til runde",
  age: "Alder",
  allowSelfJoining: "Tillat egenpåmelding (spillerne kan selv melde seg på turneringen)",
  alreadyMemberOfTeam: "Kontoen er allerede medl i dette laget.",
  averageAge: "Gjennomsnittsalder",
  averageOpponentRating: "Gjennomsnittlig ratingmotstand",
  backToTournament: "Tilbake til turneringen",
  BETA: "BETA",
  birthDate: "Fødselsdato",
  black: "Svart",
  blackWins: "Svart vinner 0-1",
  blackWon: "Seier til svart",
  board: "Brett",
  boardCards: "Bordkort",
  browse: "Naviger",
  buchholz: "FIDE Buchholz, ingen strykninger",
  buchholzCut1: "FIDE Buchholz Cut 1, dårligste strøket",
  buchholzCut2: "FIDE Buchholz Cut 2, to dårligste strøket",
  buildAndInvite: "Opprett turnering og inviter spillere",
  buildTournament: "Opprett turnering",
  bulkAccountCreation: "Opprett flere kontoer",
  byRating: "Ut ifra rating",
  carousel1: "Turneringsprogram med online spillplattform",
  carousel1Desc:
    "Enkel organisering av individuelle turneringer, lagturneringer, seriespill og hybridturneringer online og/eller over brettet. Vi har allerede implementert bl.a. Sveitser, Berger, Knockout individuelt og for lag samt manuelt oppsett",
  carousel2: "Bruksområder - formål",
  carousel2Desc:
    "Et fleksibelt og brukervennlig verktøy tilpasset prosjekter og aktiviteter i forbundsregi",
  carousel3: "SpillSjakk tilhører sjakkspillerne",
  carousel3Desc:
    "Gjennom forbundene er det norske klubbspillere som eier SpillSjakk. Det betyr at SpillSjakk alltid vil sette de aktive sjakkspillernes behov først",
  carousel4: "Bli med og påvirk!",
  carousel4Desc:
    "Bli med SpillSjakks Discord-server for de siste oppdateringene fra utviklerteamet. Delta i test-turneringer, kom med ris, ros og bidra med forslag til at SpillSjakk blir best mulig!",
  changeEmail: "Endre epost",
  changeNextPairingDateTime: "Endre tidspunkt for neste rundeoppsett",
  changePassword: "Endre passord",
  clubCount: "Antall klubber",
  clubs: "Klubber",
  confirmTournamentDeletion: "Vil du virkelig slette turneringen?",
  contact: "Kontakt",
  continueWithoutTemplate: "Fortsett uten å velge mal",
  country: "Land",
  create: "Opprett",
  createAccounts: "Opprett kontoer",
  createATeam: "Opprett et lag",
  currentPassword: "Nåværende passord",
  dateTime: "Dato og tid",
  days: "Dager",
  defaultGameLocation: "Standard plassering",
  deletePairing: "Slett rundeoppsett",
  deleteRound: "Slett runde",
  deleteTournament: "Slett turnering",
  description: "Beskrivelse",
  downloadAsCsv: "Last ned som CSV",
  draw: "Partiet ble remis",
  drawOfferPending: "Remistilbud",
  drawPoints: "Poeng for remis",
  editTournament: "Endre turneringsdetaljer", 
  email: "Epost",
  emailChanged: "Epostkontoen er endret.",
  endDate: "Sluttdato",
  featuresWeOffer: "FUNKSJONER VI TILBYR",
  federation: "Forbund",
  fideFederation: "Verdens Sjakkforbund - FIDE",
  fideNumber: "FIDE-nummer",
  fideRated: "Dette er en FIDE-ratet turnering",
  fideRating: "FIDE-rating",
  fillDateAndTime: "Sett inn dato og tid for runden",
  findTournament: "Finn en turnering",
  findTournaments: "Finn turneringer",
  finished: "Ferdig",
  firstName: "Fornavn",
  firstPairingDateTime: "Tid og dato for første rundeoppsett",
  forgotPassword: "Glemt passordet?",
  fullName: "Fullt navn",
  game: "Parti",
  gameLocationCanBeChanged: "Plassering kan endres underveis",
  games: "Partier",
  gameScore: "Partiresultat",
  goToLobby: "Gå til lobbyen",
  home: "Hjem",
  hours: "Timer",
  id: "ID",
  idAlreadyTaken: "Brukernavn er opptatt",
  ifNoOnlineGames: "Hvis det spilles kun over brettet kan du angi hvilken som helst dato og tid",
  inbox: "Innboks",
  incorrectPassword: "Ugyldig passord",
  individual: "Individuell",
  invalidCredentials: "Feil brukernavn og/eller passord.",
  invalidPasswordRecoveryCode: "Ugyldig gjenopprettingskode for passord",
  itsADraw: "Remis 1/2 -1/2",
  join: "Bli med",
  joinFor: "Bli med for",
  joinOrganization: "Bli med i en organisasjon",
  joinTournament: "Bli med i en turnering",
  knockout: "Knockout",
  lastName: "Etternavn",
  leave: "Gå ut",
  leaveTournament: "Gå ut av turneringen",
  liveAndUpcomingTournaments: "PÅGÅENDE OG KOMMENDE TURNERINGER",
  lobby: "Lobby",
  localTime: "Lokal tid",
  login: "Logg inn",
  logout: "Logg ut",
  lossPoints: "Poeng ved tap",
  manage: "Administrer",
  manageClub: "Administrer klubb",
  manageOrganization: "Administrer organisasjon",
  manageParticipants: "Organiser deltakere",
  manageRoundsAndPairings: "Organiser rundeoppsett",
  manageTeamPlayers: "Organiser spillere i laget",
  manageTournament: "Organiser turnering",
  manualPairing: "Manuelt oppsett",
  matchScore: "Kampresultat",
  medianBuchholz: "Median Buchholz, dårligste og beste strøket",
  medianBuchholz2: " Median Buchholz 2, to dårligste og to beste strøket",
  members: "Medlemmer",
  membersPerTeam: "Spillere per lag",
  messageMembers: "Send melding til medlemmer",
  mfRatio: "M/F ratio",
  minutes: "minutter",
  myTeams: "Mine lag",
  myTournamentCalendar: "Min turneringskalender",
  name: "Navn",
  nameOfThePlayer: "Spillerens navn eller FIDE-id",
  navbarAccountCreation: "OPPRETT KONTO",
  navbarInfo: "INFO",
  navbarLogin: "LOGG INN",
  navbarOrgs: "ORGANISASJONER",
  navbarTournaments: "TURNERINGER",
  newPassword: "Nytt passord",
  newPasswordAgain: "Gjenta nytt passord",
  nextGame: "Neste parti",
  nextGameIn: "Neste parti starter om",
  nextOnlinePairingWillBeAt: "Neste online rundeoppsett kommer",
  nextRoundText: "Neste runde starter om:",
  no: "Nei",
  notParticipating: "Deltar ikke",
  noUpcomingGames: "Det er ikke satt opp noen partier for deg enda.",
  numberOfRounds: "Antall runder",
  offerDraw: "Tilby remis",
  ongoing: "Pågående",
  ongoingTournaments: "Pågående turneringer",
  online: "Online",
  onlinePairingInterval: "Intervall mellom runder online",
  onlyShowScoresOfTop: "Velg antall spillere eller lag som skal vises med resultat på listene",
  organiser: "Arrangør",
  organizations: "Organisasjoner",
  organizationStatistics: "Statistikk for organisasjonoen",
  otb: "Over brettet",
  otherClubMembers: "Andre klubbmedlemmer",
  pageNotFound: "Siden ikke funnet",
  pairingPrintouts: "Utskrift rundeoppsett",
  pairings: "Rundeoppsett",
  participant: "Deltaker",
  participants: "Deltakere",
  participating: "Deltar",
  password: "Passord",
  passwordChanged: "Passord har blitt endret",
  passwordRecoveryEmailSent: "Epost med lenke til gjenoppretting av passord er sendt til deg.",
  passwords: "Passord",
  passwordsAreNotEqual: "Tassordene er ikke like",
  permissions: "Tillatelser",
  play: "Spill",
  player: "Spiller",
  playerCount: "Antall spillere",
  playersPerTeam: "Antall spillere per lag",
  playGame: "Spill parti",
  privateTournament: "Dette er en privat turnering.",
  productDescription: "Enkel og sikker turneringsadministrasjon.",
  productName: "SpillSjakk",
  profile_picture: "Profilbilde",
  profilePicturePlaceholder: "Sett inn url til bilde",
  provisionalFideRating: "Midlertidig FIDE-rating",
  publiclyViewable: "Offentlig synlig",
  random: "Tilfeldig",
  rating: "Rating",
  rawPgn: "PGN",
  recover: "Gjenopprett",
  recoverAccount: "Gjenopprett konto",
  region: "Region",
  remove: "Fjerne",
  resign: "Gi opp",
  result: "Resultat",
  resultPrintouts: "Utskrift resultatliste",
  reviewGame: "Se på partiet",
  round: "Runde",
  roundNb: "Antall runder",
  rounds: "runder",
  score: "Resultat",
  searchEllipsis: "Søk...",
  searchTournaments: "Finn turneringer",
  seconds: "sekunder",
  seed: "Rangere",
  seeding: "Rangering",
  send: " Send",
  sex: "Kjønn",
  spectate: "Se på",
  standings: "Oversikt",
  start: "Start",
  startDate: "Startdato",
  startsIn: "Starter om:",
  statistics: "Statistikk",
  submit: "Send inn",
  suggestedAccounts: "Foreslåtte kontoer",
  suggestedOrganizations: "Foreslått organisasjoner",
  swissDutch: "Swiss Dutch",
  team: "Lag",
  teamKnockout: "Knockout for lag",
  teamKonrad: "Konrad for lag",
  teamManager: "Lagleder",
  teamMonrad: "SkoleSjakken",
  teamOlympiad: "Olympisk for lag",
  teams: "Lag",
  teamSwissDutch: "Sveitser for lag",
  theUrlForThisTeam: "URL for dette laget blir /team/view/<id>",
  theUrlForThisTournament: "URL  til denne turneringen blir /tournament/view/<id>",
  thisIsTheOnlyTimeYouSeeThesePasswords:  "Se brukernavn og passord for kontoene her. Du ser passordene kun nå!",
  tiebreaker: "Rangering",
  timeControl: "Tidskontroll",
  title: "Tittel",
  totalClubCount: "Totalt antall klubber",
  totalPlayerCount: "Totalt antall spillere",
  tournament: "Turnering",
  tournamentName: "Turneringsnavn",
  tournamentOrganizer: "Turneringsleder",
  tournaments: "Turneringer",
  type: "Type",
  upcomingTournaments: "Kommende turneringer",
  update: "Oppdater",
  userGuide: "Brukerhåndbok",
  username: "Brukernavn",
  viewGame: "Se parti",
  waitingForGame: " Vente på neste parti",
  weeks: "uker",
  weighted: "Vektet",
  white: "Hvit",
  whiteWins: "Hvit vinner, 1-0",
  whiteWon: "Seier til hvit",
  winPoints: "Poeng for seier",
  yes: "Ja",
};

export { no };
