/* eslint-disable prettier/prettier */
const no = {
	"403": "403 - Forbudt, du er ikke innlogget og har ingen tilgang.",
	"404": "404 - Ressurs ikke tilgjengelig, hvis du mener dette er feil - sjekk at du er innlogget.",
	"500": "500 - Intern feil på server",
	"BETA": "BETA",
	"about": "Om",
	"aboutToPlay": "Partiet ditt starter snart!",
	"acceptDraw": "Aksepter remis?",
	"accountDoesNotExist": "Kontoen eksisterer ikke.",
	"accountHasNoEmail": "Kontoen er opprettet uten e-post ",
	"accountList": "Kontoliste",
	"accountSettings": "Kontoinnstillinger",
	"add": "Legg til",
	"addATeam": "Legg til et lag",
	"addClub": "Legg til en klubb",
	"addClubId": "",
	"addMember": "Legg til medlem",
	"addOtherAccount": "Legg til en konto",
	"addPairing": "Legg til rundeoppsett",
	"addParticipantsWithAccount": "Legg til deltakere med konto",
	"addParticipantsWithoutAccount": "Legg til deltakere uten konto",
	"addPlayerId": "",
	"addRound": "Legg til runde",
	"age": "Alder",
	"allowSelfJoining": "Tillat egenpåmelding (spillerne kan selv melde seg på turneringen)",
	"alreadyHaveAccount": "",
	"alreadyMemberOfTeam": "Kontoen er allerede medl i dette laget.",
	"areYouAtSpillsjakkDiscord": "Er du i SpillSjakks Discord-server?",
	"averageAge": "Gjennomsnittsalder",
	"averageOpponentRating": "Gjennomsnittlig ratingmotstand",
	"backToTournament": "Tilbake til turneringen",
	"banner_picture": "",
	"birthDate": "Fødselsdato",
	"black": "Svart",
	"blackWins": "Svart vinner 0-1",
	"blackWon": "Seier til svart",
	"board": "Brett",
	"boardCards": "Bordkort",
	"browse": "Naviger",
	"browseClubs": "",
	"browseOrgs": "",
	"browseOrgsAndClubs": "",
	"buchholz": "FIDE Buchholz, ingen strykninger",
	"buchholzCut1": "FIDE Buchholz Cut 1, dårligste strøket",
	"buchholzCut2": "FIDE Buchholz Cut 2, to dårligste strøket",
	"buildAndInvite": "Opprett turnering og inviter spillere",
	"buildTournament": "Opprett turnering",
	"bulkAccountCreation": "Opprett flere kontoer",
	"byRating": "Ut ifra rating",
	"carousel1": "Turneringsprogram med online spillplattform",
	"carousel1Desc": "Enkel organisering av individuelle turneringer, lagturneringer, seriespill og hybridturneringer online og/eller over brettet. Vi har allerede implementert bl.a. Sveitser, Berger, Knockout individuelt og for lag samt manuelt oppsett",
	"carousel2": "Bruksområder - formål",
	"carousel2Desc": "Et fleksibelt og brukervennlig verktøy tilpasset prosjekter og aktiviteter i forbundsregi",
	"carousel3": "SpillSjakk tilhører sjakkspillerne",
	"carousel3Desc": "Gjennom forbundene er det norske klubbspillere som eier SpillSjakk. Det betyr at SpillSjakk alltid vil sette de aktive sjakkspillernes behov først",
	"carousel4": "Bli med og påvirk!",
	"carousel4Desc": "Bli med SpillSjakks Discord-server for de siste oppdateringene fra utviklerteamet. Delta i test-turneringer, kom med ris, ros og bidra med forslag til at SpillSjakk blir best mulig!",
	"changeEmail": "Endre epost",
	"changeNextPairingDateTime": "Endre tidspunkt for neste rundeoppsett",
	"changePassword": "Endre passord",
	"clickToCopy": "",
	"clubCount": "Antall klubber",
	"clubInvitations": "",
	"clubYouHaveBeenInvited": "",
	"clubs": "Klubber",
	"confirmTournamentDeletion": "Vil du virkelig slette turneringen?",
	"confirmTournamentWithVisibleNames": "",
	"congrats": "Gratulerer",
	"contact": "Kontakt",
	"continue": "",
	"continueWithoutTemplate": "Fortsett uten å velge mal",
	"copied": "",
	"country": "Land",
	"create": "Opprett",
	"createATeam": "Opprett et lag",
	"createAccounts": "Opprett kontoer",
	"createYourAccount": "",
	"currentPassword": "Nåværende passord",
	"custom": "",
	"dateTime": "Dato og tid",
	"days": "Dager",
	"defaultGameLocation": "Standard plassering",
	"deletePairing": "Slett rundeoppsett",
	"deleteRound": "Slett runde",
	"deleteTournament": "Slett turnering",
	"description": "Beskrivelse",
	"downloadAsCsv": "Last ned som CSV",
	"draw": "Partiet ble remis",
	"drawOfferPending": "Remistilbud",
	"drawPoints": "Poeng for remis",
	"editTournament": "Endre turneringsdetaljer",
	"email": "Epost",
	"emailChanged": "Epostkontoen er endret.",
	"endDate": "Sluttdato",
	"expandAll": "",
	"featuresWeOffer": "FUNKSJONER VI TILBYR",
	"federation": "Forbund",
	"fideFederation": "Verdens Sjakkforbund - FIDE",
	"fideInfoText": "",
	"fideNumber": "FIDE-nummer",
	"fideRated": "Dette er en FIDE-ratet turnering",
	"fideRating": "FIDE-rating",
	"fillDateAndTime": "Sett inn dato og tid for runden",
	"findTournament": "Finn en turnering",
	"findTournaments": "Finn turneringer",
	"findoutFide": "",
	"finished": "Ferdig",
	"firstName": "Fornavn",
	"firstPairingDateTime": "Tid og dato for første rundeoppsett",
	"flaggingTime": "Flagging time!",
	"forgotPassword": "Glemt passordet?",
	"fullName": "Fullt navn",
	"game": "Parti",
	"gameLocationCanBeChanged": "Plassering kan endres underveis",
	"gameScore": "Partiresultat",
	"games": "Partier",
	"gender": "",
	"getInTouch": "",
	"goToLobby": "Gå til lobbyen",
	"goodGame": "Godt parti",
	"greatEndgame": "Bra sluttspill teknikk",
	"hello": "Hei",
	"home": "Hjem",
	"hours": "Timer",
	"iDidntNeedThatPiece": "Jeg trengte ikke den brikken likevel",
	"iLikeYourOpening": "Liker åpningen din",
	"iNeedtoRethink": "Jeg trenger å revurdere min tilnærming til sjakk",
	"id": "ID",
	"idAlreadyTaken": "Brukernavn er opptatt",
	"ifNoOnlineGames": "Hvis det spilles kun over brettet kan du angi hvilken som helst dato og tid",
	"inbox": "Innboks",
	"incorrectPassword": "Ugyldig passord",
	"individual": "Individuell",
	"invalidCredentials": "Feil brukernavn og/eller passord.",
	"invalidPasswordRecoveryCode": "Ugyldig gjenopprettingskode for passord",
	"invite": "",
	"itsADraw": "Remis 1/2 -1/2",
	"join": "Bli med",
	"joinFor": "Bli med for",
	"joinOrganization": "Bli med i en organisasjon",
	"joinTournament": "Bli med i en turnering",
	"knockout": "Knockout",
	"lastName": "Etternavn",
	"leave": "Gå ut",
	"leaveTournament": "Gå ut av turneringen",
	"letsPlayAgain": "La oss spille igjen en gang",
	"liveAndUpcomingTournaments": "PÅGÅENDE OG KOMMENDE TURNERINGER",
	"lobby": "Lobby",
	"localTime": "Lokal tid",
	"login": "Logg inn",
	"loginAndTryAgain": "",
	"loginFirst": "",
	"logout": "Logg ut",
	"lossPoints": "Poeng ved tap",
	"manage": "Administrer",
	"manageClub": "Administrer klubb",
	"manageClub_aboutClub": "",
	"manageClub_aboutClubDesc": "",
	"manageClub_accounts": "",
	"manageClub_addNewTeam": "",
	"manageClub_address": "",
	"manageClub_addressDesc": "",
	"manageClub_bannerPhoto": "",
	"manageClub_bannerPhotoDesc": "",
	"manageClub_clubsId": "",
	"manageClub_clubsIdDesc": "",
	"manageClub_clubsName": "",
	"manageClub_clubsNameDesc": "",
	"manageClub_email": "",
	"manageClub_emailDesc": "",
	"manageClub_profilePhoto": "",
	"manageClub_profilePhotoDesc": "",
	"manageClub_teamCaptainPackage": "",
	"manageClub_teamCaptainPackageDesc": "",
	"manageClub_teamsInClub": "",
	"manageClub_totalPlayerCount": "",
	"manageClub_totalTeamCount": "",
	"manageClub_website": "",
	"manageClub_websiteDesc": "",
	"manageOrg_aboutOrg": "",
	"manageOrg_address": "",
	"manageOrg_addressDesc": "",
	"manageOrg_allPowersPackage": "",
	"manageOrg_allPowersPackageDesc": "",
	"manageOrg_arbiterPowersPackage": "",
	"manageOrg_arbiterPowersPackageDesc": "",
	"manageOrg_bannerPhoto": "",
	"manageOrg_bannerPhotoDesc": "",
	"manageOrg_editorPowersPackage": "",
	"manageOrg_editorPowersPackageDesc": "",
	"manageOrg_email": "",
	"manageOrg_emailDesc": "",
	"manageOrg_orgsAccounts": "",
	"manageOrg_orgsClubs": "",
	"manageOrg_orgsDesc": "",
	"manageOrg_orgsDescDesc": "",
	"manageOrg_orgsId": "",
	"manageOrg_orgsIdDesc": "",
	"manageOrg_orgsName": "",
	"manageOrg_orgsNameDesc": "",
	"manageOrg_profilePhoto": "",
	"manageOrg_profilePhotoDesc": "",
	"manageOrg_sharePower": "",
	"manageOrg_totalClubCount": "",
	"manageOrg_totalPlayerCount": "",
	"manageOrg_website": "",
	"manageOrg_websiteDesc": "",
	"manageOrganization": "Administrer organisasjon",
	"manageParticipants": "Organiser deltakere",
	"manageRoundsAndPairings": "Organiser rundeoppsett",
	"manageTeamPlayers": "Organiser spillere i laget",
	"manageTournament": "Organiser turnering",
	"manualPairing": "Manuelt oppsett",
	"matchScore": "Kampresultat",
	"medianBuchholz": "Median Buchholz, dårligste og beste strøket",
	"medianBuchholz2": " Median Buchholz 2, to dårligste og to beste strøket",
	"members": "Medlemmer",
	"membersPerTeam": "Spillere per lag",
	"messageJustToTeamMembers": "",
	"messageMembers": "Send melding til medlemmer",
	"mfRatio": "M/F ratio",
	"minutes": "minutter",
	"mouseSlip": "Argh! Mouseslip",
	"myTeams": "Mine lag",
	"myTournamentCalendar": "Min turneringskalender",
	"name": "Navn",
	"nameOfThePlayer": "Spillerens navn eller FIDE-id",
	"namePrivacyInfo": "",
	"navbarAccountCreation": "OPPRETT KONTO",
	"navbarInfo": "INFO",
	"navbarLogin": "LOGG INN",
	"navbarOrgs": "ORGANISASJONER",
	"navbarTournaments": "TURNERINGER",
	"newPassword": "Nytt passord",
	"newPasswordAgain": "Gjenta nytt passord",
	"next": "",
	"nextGame": "Neste parti",
	"nextGameIn": "Neste parti starter om",
	"nextOnlinePairingWillBeAt": "Neste online rundeoppsett kommer",
	"nextRoundText": "Neste runde starter om:",
	"niceTactic": "Glimrende taktikk",
	"no": "Nei",
	"noUpcomingGames": "Det er ikke satt opp noen partier for deg enda.",
	"notDisplayedPublicly": "",
	"notFound": "",
	"notParticipating": "Deltar ikke",
	"numberOfRounds": "Antall runder",
	"off": "",
	"offerDraw": "Tilby remis",
	"on": "",
	"oneClickJoin": "",
	"ongoing": "Pågående",
	"ongoingTournaments": "Pågående turneringer",
	"online": "Online",
	"onlinePairingInterval": "Intervall mellom runder online",
	"onlyShowScoresOfTop": "Velg antall spillere eller lag som skal vises med resultat på listene",
	"opponent": "",
	"organiser": "Arrangør",
	"organizationInvitations": "",
	"organizationStatistics": "Statistikk for organisasjonoen",
	"organizations": "Organisasjoner",
	"otb": "Over brettet",
	"otherClubMembers": "Andre klubbmedlemmer",
	"pageNotFound": "Siden ikke funnet",
	"pairingPrintouts": "Utskrift rundeoppsett",
	"pairings": "Rundeoppsett",
	"participant": "Deltaker",
	"participants": "Deltakere",
	"participating": "Deltar",
	"password": "Passord",
	"passwordChanged": "Passord har blitt endret",
	"passwordRecoveryEmailSent": "Epost med lenke til gjenoppretting av passord er sendt til deg.",
	"passwords": "Passord",
	"passwordsAreNotEqual": "Tassordene er ikke like",
	"permissions": "Tillatelser",
	"play": "Spill",
	"playGame": "Spill parti",
	"player": "Spiller",
	"playerCount": "Antall spillere",
	"players": "",
	"playersPerTeam": "Antall spillere per lag",
	"pleaseSelect": "",
	"privacyPolicy": "",
	"privateTournament": "Dette er en privat turnering.",
	"productDescription": "Enkel og sikker turneringsadministrasjon.",
	"productName": "SpillSjakk",
	"profilePicturePlaceholder": "Sett inn url til bilde",
	"profile_picture": "Profilbilde",
	"provisionalFideRating": "Midlertidig FIDE-rating",
	"publiclyViewable": "Offentlig synlig",
	"random": "Tilfeldig",
	"rating": "Rating",
	"rawPgn": "PGN",
	"recover": "Gjenopprett",
	"recoverAccount": "Gjenopprett konto",
	"region": "Region",
	"remove": "Fjerne",
	"resign": "Gi opp",
	"result": "Resultat",
	"resultPrintouts": "Utskrift resultatliste",
	"reviewGame": "Se på partiet",
	"round": "Runde",
	"roundNb": "Antall runder",
	"roundRobin": "Round Robin",
	"rounds": "runder",
	"saveUpdates": "",
	"score": "Resultat",
	"searchByFideId": "",
	"searchEllipsis": "Søk...",
	"searchTournaments": "Finn turneringer",
	"seconds": "sekunder",
	"seed": "Rangere",
	"seeding": "Rangering",
	"send": " Send",
	"setup": "",
	"setupRound": "",
	"sex": "Kjønn",
	"showOnlyUsernames": "",
	"spectate": "Se på",
	"standings": "Oversikt",
	"start": "Start",
	"startDate": "Startdato",
	"startTyping": "",
	"startsIn": "Starter om:",
	"statistics": "Statistikk",
	"submit": "Send inn",
	"suggestedAccounts": "Foreslåtte kontoer",
	"suggestedOrganizations": "Foreslått organisasjoner",
	"swissDutch": "Swiss Dutch",
	"team": "Lag",
	"teamKnockout": "Knockout for lag",
	"teamKonrad": "Konrad for lag",
	"teamManager": "Lagleder",
	"teamMonrad": "SkoleSjakken",
	"teamOlympiad": "Olympisk for lag",
	"teamRoundRobin": "",
	"teamSwissDutch": "Sveitser for lag",
	"teams": "Lag",
	"thankYouForGame": "Takk for partiet",
	"theUrlForThisTeam": "URL for dette laget blir /team/view/<id>",
	"theUrlForThisTournament": "URL  til denne turneringen blir /tournament/view/<id>",
	"thisIsTheOnlyTimeYouSeeThesePasswords": "Se brukernavn og passord for kontoene her. Du ser passordene kun nå!",
	"tiebreaker": "Rangering",
	"timeControl": "Tidskontroll",
	"title": "Tittel",
	"toMakeFirstMove": "",
	"totalClubCount": "Totalt antall klubber",
	"totalPlayerCount": "Totalt antall spillere",
	"tournament": "Turnering",
	"tournamentHomepage": "",
	"tournamentName": "Turneringsnavn",
	"tournamentOrganizer": "Turneringsleder",
	"tournaments": "Turneringer",
	"type": "Type",
	"upcomingTournaments": "Kommende turneringer",
	"update": "Oppdater",
	"userGuide": "Brukerhåndbok",
	"username": "Brukernavn",
	"usernameExists": "",
	"viewGame": "Se parti",
	"waitingForGame": " Vente på neste parti",
	"weeks": "uker",
	"weighted": "Vektet",
	"wellPlayed": "Bra spilt",
	"whatIsFide": "",
	"white": "Hvit",
	"whiteWins": "Hvit vinner, 1-0",
	"whiteWon": "Seier til hvit",
	"whyFide": "",
	"winPoints": "Poeng for seier",
	"yes": "Ja",
	"you": "",
	"youHaveBeenInvited": ""
};

export { no };
