/* eslint-disable */
export default {
  "title1": "Terms of Service - User Agreement",
  "p1_1": "In summary - be most excellent towards each other, act legally, and have fun.",
  "p1_2": "Please read through all of this Agreement carefully before using our website. Without impacting your statutory rights, this Agreement is legally binding between us. By using our website, you accept the terms in this Agreement in full. Accordingly, If you don’t agree, you must not use our website.",
  "p1_3": "If or when you register with our website, submit any content to our website or use any of our website services, we will ask you to expressly agree to this Agreement. You agree you are responsible for compliance with any applicable local laws.",
  "p1_4": "By using our website or accepting the terms of this Agreement, you confirm and represent that you are an adult of legal age, or have been given permission and consent by a parent or legal guardian who is over the age of 18 to enter into this Agreement.",
  "p1_5": "The materials contained in this website are protected by the applicable copyright and trademark laws. ",
  "title2": "User License",
  "p2_1": "Permission is granted to temporarily view, download, print, cache, stream and use any other of our website services by means of a web browser on our website for personal, non-commercial transitory usage only, subject to the other provisions of this Agreement. This is the grant of a license, not a transfer of title, and under this license you may not:",
  "p2_2": "modify or copy the materials, unless a specific license allows you to do so and you comply fully with that license;",
  "p2_3": "use the materials for any commercial purpose, or for any commercial public display unless a specific license allows you to do so and you comply fully with that license;",
  "p2_4": "attempt to decompile or reverse engineer any software contained on our website, unless a specific license allows you to do so and you comply fully with that license;",
  "p2_5": "remove any copyright or other proprietary notation from our website;",
  "p2_6": "transfer the materials to another person or mirror the materials on any other server, unless a specific license allows you to do so and you comply fully with that license.",
  "p2_7": "This license shall automatically terminate if you violate any of these restrictions, subject to the other provisions of this Agreement, and you agree that we may, with or without cause and without prior notice, immediately terminate your spillsjakk.no account, associated email address, and access to our website. You agree all terminations shall be made in spillsjakk.no’s sole discretion and that spillsjakk.no shall not be liable to you or any third party for any termination of your account, associated email address, or access to the website.",
  "title3": "Acceptable Use",
  "p3_1": "You must not use our website in any way or take any action that does cause or may cause damage to our website, provision of services, infrastructure, or the performance, availability or accessibility of the website, provision of services, and infrastructure. Further, you may not use our website in any way that is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful activity. You may not conduct any systematic or automated data collection activities (including without limitation scraping, data mining, data extraction and data harvesting) on or in relation to our website without our explicit written consent, or interact with our website using any robot, spider or other automated means except for search engine indexing. You may not use data collected from our website for any direct marketing activity, or to contact individuals, companies or other persons or entities.",
  "title4": "Disclaimer",
  "p4_1": "The materials on our website are provided “as is”. We make no warranties, expressed or implied and hereby disclaim and negate all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose or non-infringement of intellectual property or other violation of rights. Further, we do not warrant or make any representations concerning the accuracy, likely results of reliability of the use of the materials on our website or otherwise relating to such materials on any sites linked to this site.",
  "title5": "Limitations",
  "p5_1": "In no event shall we or our suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, damages for harm, or due to business interruption) arising out of the use or inability to use the materials on our website, regardless of the actions we may or may not have taken, to the fullest extent afforded by the law of Norway.",
  "title6": "Revisions & Errata",
  "p6_1": "The materials appearing on our website could include technical, typographical, or photographic and graphical errors. We do not warrant that any of the materials on our website are accurate, complete or current. We may make changes to the materials contained on our website at any time without notice. We do not make any commitment to update the materials.",
  "title7": "Links",
  "p7_1": "We have not reviewed all of the sites linked to in our website and we are not responsible for the contents of any such linked third party site. The inclusion of any link does not imply endorsement by us of that website. Use of any such linked web site is at the user’s own risk.",
  "title8": "Site Terms of Use Modifications",
  "p8_1": "We may revise this Agreement at any time without notice, to the fullest extent afforded to us by the law of Norway. By using this website you agree to be bound by the then current version of this Agreement, and when changed, your continued use will be taken for acceptance of the new Agreement. ",
  "title9": "Assignment",
  "p9_1": "You hereby agree that we may assign, transfer, sub-contract or otherwise deal with our rights and/or obligations under this Agreement, and you may not without our prior written consent assign, transfer, sub-contract or otherwise deal with any of your rights and/or obligations under these terms and conditions.",
  "title10": "Severability",
  "p10_1": "If a provision of this Agreement is determined by any court or other competent authority to be unlawful and/or unenforceable, the other provisions will continue in effect.",
  "title11": "Jurisdiction",
  "p11_1": "Any claim relating to our website shall be governed by the laws of Norway, without regard to its conflict of law provisions.",
  "title12": "Informal Resolution",
  "p12_1": "You will first contact us at hei@spillsjakk.no to give us notice of any dispute and attempt to resolve it with us informally. We will attempt in good faith to negotiate a resolution of the dispute for at least thirty (30) days from the date we receive your correspondence.",
  "p12_2": "Certain organisers of events may have their own path of informal resolution, potentially including their own appeals committees, commissions, or panels. Where this is the case, you agree to follow their procedures and waive us of liability where the dispute is covered by another party’s Terms.",
  "title13": "Fair Play & Community Guidelines",
  "p13_1": "Our website has the duty and responsibility to maintain a fair platform for chess players. We reserve the right to monitor all chess games played on our website, to take statistics and metrics of the chess games played on our website, and in-line with our privacy policy, to share these games where our own contractual agreements rely on the sharing of those data, metrics, and statistics.",
  "p13_2": "It is our sole discretion as to whether our Fair Play & Community Guidelines have been violated. We reserve the right to close accounts without warning, and to withdraw our services from those we have found to have violated our Fair Play & Community Guidelines. ",
  "p13_3": "Your moves must be your own",
  "p13_4": "You must keep your password private",
  "p13_5": "You agree to take responsibility for the security of your account",
  "p13_6": "You are not allowed to cheat",
  "p13_7": "You may not seek external assistance, whether from another person or from software or other resources",
  "p13_8": "You may not impersonate someone you are not",
  "p13_9": "You may not share your Player account with anyone else",
  "p13_10": "You may not play from another Player account other than your own",
  "p13_11": "You may not artificially manipulate ratings, matches or results",
  "p13_12": "You may not interfere with another person’s game",
  "p13_13": "You may not try to access another person’s account",
  "p13_14": "You may not act in a harassing, threatening, or stalk our users",
  "p13_15": "You may not share materials you do not have the rights to share",
  "p13_16": "You agree to act in accordance with the laws of Norway",
  "p13_17": "You agree to treat others kindly and with care",
  "p13_18": "This list is non-exhaustive and subject to change. "
}